pub mod project;

use codeguard_ast::{extract_file_info, FileInfo};
use codeguard_core::diagnostic::TextEdit;
use codeguard_core::{Diagnostic, RuleCode, Span};
use once_cell::sync::Lazy;
use regex::Regex;
use std::path::Path;
use tree_sitter::Tree;

static SECRET_NAME_RE: Lazy<Regex> = Lazy::new(|| {
    Regex::new(r"(?i)(api[_-]?key|secret[_-]?key|password|passwd|token|auth[_-]?token|secret|private[_-]?key|access[_-]?key|client[_-]?secret)")
        .unwrap()
});

static AI_COMMENT_RE: Lazy<Regex> = Lazy::new(|| {
    Regex::new(r"(?i)(claude|copilot|chatgpt|gpt-4|gpt-3\.5|gpt4|gemini|anthropic|openai|cursor|ai[- ]generated|llm[- ]generated|generated by ai|generated by claude|generated by copilot|generated by chatgpt|TODO:?\s*(claude|copilot|chatgpt|ai)\s)")
        .unwrap()
});

static SUSPICIOUS_ROUTE_RE: Lazy<Regex> = Lazy::new(|| {
    Regex::new(r"/(debug|test|internal|admin|_dev|__debug__|phpinfo|server-status)/")
        .unwrap()
});

static AUTH_DECORATOR_RE: Lazy<Regex> = Lazy::new(|| {
    Regex::new(r"(?i)(auth|login_required|permission|protect|secure|require_auth|authenticated|jwt_required|token_required)")
        .unwrap()
});

static ROUTE_DECORATOR_RE: Lazy<Regex> = Lazy::new(|| {
    Regex::new(r"(app\.route|router\.(get|post|put|delete|patch)|Blueprint\.route|api_view|app\.(get|post|put|delete|patch))")
        .unwrap()
});

static SOURCE_MAP_RE: Lazy<Regex> = Lazy::new(|| {
    Regex::new(r#"(sourceMappingURL|\.map['"])"#)
        .unwrap()
});

const DEBUG_FUNCTIONS: &[&str] = &[
    "print",
    "breakpoint",
];

const DEBUG_QUALIFIED: &[(&str, &str)] = &[
    ("pdb", "set_trace"),
    ("console", "log"),
    ("console", "error"),
    ("console", "warn"),
    ("console", "debug"),
];

const PDB_MODULES: &[&str] = &["pdb", "ipdb", "pudb"];

pub fn lint_vibe(tree: &Tree, source: &str, path: &Path) -> Vec<Diagnostic> {
    let info = extract_file_info(tree, source, path);
    let mut diagnostics = Vec::new();

    check_hardcoded_secrets(&info, &mut diagnostics);
    check_ai_comments(&info, &mut diagnostics);
    check_debug_calls(&info, &mut diagnostics);
    check_pdb_imports(&info, &mut diagnostics);
    check_source_maps(&info, source, path, &mut diagnostics);
    check_suspicious_endpoints(&info, &mut diagnostics);

    diagnostics
}

fn check_hardcoded_secrets(info: &FileInfo, diags: &mut Vec<Diagnostic>) {
    let mut reported_lines: std::collections::HashSet<u32> = std::collections::HashSet::new();

    for assign in &info.assignments {
        if !assign.value_is_string {
            continue;
        }
        let value = assign.value.as_deref().unwrap_or("");
        let unquoted = value
            .trim_start_matches(|c: char| c == '\'' || c == '\"')
            .trim_end_matches(|c: char| c == '\'' || c == '\"');
        if unquoted.is_empty() || unquoted == "None" || value.contains("os.") {
            continue;
        }

        // Check 1: variable name matches secret pattern (original VC001)
        let name_match = SECRET_NAME_RE.is_match(&assign.target);

        // Check 2: high-entropy string (Shannon entropy > 4.5, length >= 16)
        let entropy_match = unquoted.len() >= 16 && shannon_entropy(unquoted) > 4.5;

        // Check 3: known secret prefixes (sk-, ghp_, AKIA, eyJ for JWT)
        let prefix_match = has_secret_prefix(unquoted);

        if !name_match && !entropy_match && !prefix_match {
            continue;
        }

        reported_lines.insert(assign.span.start_line);

        let env_var = assign.target.to_uppercase();
        let replacement = make_environ_ref(&env_var);
        let suggestion_text = if name_match {
            format!("use {} instead", replacement)
        } else if prefix_match {
            format!("looks like a secret token (prefix match); use {} instead", replacement)
        } else {
            format!("high-entropy string (likely a secret); use {} instead", replacement)
        };
        let fix = assign.value_span.as_ref().map(|vs| TextEdit {
            start_line: vs.start_line,
            start_col: vs.start_col,
            end_line: vs.end_line,
            end_col: vs.end_col,
            replacement: replacement.clone(),
        });

        let mut d = Diagnostic::warning(
            RuleCode::new("VC001"),
            assign.span.clone(),
            format!("hardcoded secret: {} = {}", assign.target, truncate_secret(value)),
        )
        .with_suggestion(suggestion_text);

        if let Some(fix) = fix {
            d = d.with_fix(fix);
        }
        diags.push(d);
    }
}

fn check_ai_comments(info: &FileInfo, diags: &mut Vec<Diagnostic>) {
    for comment in &info.comments {
        if AI_COMMENT_RE.is_match(&comment.text) {
            let fix = TextEdit {
                start_line: comment.span.start_line,
                start_col: 0,
                end_line: comment.span.end_line,
                end_col: comment.span.end_col,
                replacement: String::new(),
            };
            diags.push(
                Diagnostic::info(
                    RuleCode::new("VC002"),
                    comment.span.clone(),
                    format!("AI artifact: {}", comment.text.trim()),
                )
                .with_suggestion("remove AI-generated comment")
                .with_fix(fix),
            );
        }
    }
}

fn check_debug_calls(info: &FileInfo, diags: &mut Vec<Diagnostic>) {
    for call in &info.calls {
        let is_debug = DEBUG_FUNCTIONS.contains(&call.function.as_str())
            && call.receiver.is_none()
            || DEBUG_QUALIFIED.iter().any(|(recv, func)| {
                call.receiver.as_deref() == Some(*recv) && call.function == *func
            });

        if is_debug {
            let name = &call.full_name;
            let fix = TextEdit {
                start_line: call.span.start_line,
                start_col: 0,
                end_line: call.span.end_line,
                end_col: call.span.end_col,
                replacement: String::new(),
            };
            diags.push(
                Diagnostic::warning(
                    RuleCode::new("VC003"),
                    call.span.clone(),
                    format!("debug code: {name}() call"),
                )
                .with_suggestion("remove debug statement")
                .with_fix(fix),
            );
        }
    }
}

fn check_pdb_imports(info: &FileInfo, diags: &mut Vec<Diagnostic>) {
    for import in &info.imports {
        if PDB_MODULES.contains(&import.module.as_str()) {
            let fix = TextEdit {
                start_line: import.span.start_line,
                start_col: 0,
                end_line: import.span.end_line,
                end_col: import.span.end_col,
                replacement: String::new(),
            };
            diags.push(
                Diagnostic::warning(
                    RuleCode::new("VC004"),
                    import.span.clone(),
                    format!("debug import: {}", import.module),
                )
                .with_suggestion("remove debug import")
                .with_fix(fix),
            );
        }
    }
}

fn check_source_maps(
    info: &FileInfo,
    source: &str,
    path: &Path,
    diags: &mut Vec<Diagnostic>,
) {
    // Check comments for sourceMappingURL
    for comment in &info.comments {
        if SOURCE_MAP_RE.is_match(&comment.text) {
            diags.push(Diagnostic::warning(
                RuleCode::new("VC005"),
                comment.span.clone(),
                "source map reference exposed".to_string(),
            ));
        }
    }

    // Check string literals
    for assign in &info.assignments {
        if let Some(ref val) = assign.value {
            if SOURCE_MAP_RE.is_match(val) {
                diags.push(Diagnostic::warning(
                    RuleCode::new("VC005"),
                    assign.span.clone(),
                    "source map reference in string literal".to_string(),
                ));
            }
        }
    }

    // Check file extension itself
    if let Some(ext) = path.extension() {
        if ext == "map" {
            let span = Span::new(path.to_path_buf(), 1, 0, 1, 0);
            diags.push(Diagnostic::warning(
                RuleCode::new("VC005"),
                span,
                "source map file exposed".to_string(),
            ));
        }
    }

    // Check for sourceMappingURL in raw source (catches cases not in comments)
    for (i, line) in source.lines().enumerate() {
        if line.contains("sourceMappingURL") {
            let already_reported = info
                .comments
                .iter()
                .any(|c| c.span.start_line == (i as u32 + 1) && c.text.contains("sourceMappingURL"));
            if !already_reported {
                diags.push(Diagnostic::warning(
                    RuleCode::new("VC005"),
                    Span::new(path.to_path_buf(), i as u32 + 1, 0, i as u32 + 1, line.len() as u32),
                    "source map reference exposed".to_string(),
                ));
            }
        }
    }
}

fn check_suspicious_endpoints(info: &FileInfo, diags: &mut Vec<Diagnostic>) {
    for dec in &info.decorators {
        if !ROUTE_DECORATOR_RE.is_match(&dec.name) {
            continue;
        }
        for arg in &dec.arguments {
            if !SUSPICIOUS_ROUTE_RE.is_match(arg) {
                continue;
            }
            // Check if any auth decorator is present on the same function
            let has_auth = dec
                .function_decorators
                .iter()
                .any(|d| AUTH_DECORATOR_RE.is_match(d));
            if !has_auth {
                diags.push(
                    Diagnostic::warning(
                        RuleCode::new("VC006"),
                        dec.span.clone(),
                        format!("suspicious endpoint '{arg}' without auth decorator"),
                    )
                    .with_suggestion("add an authentication decorator (e.g., @login_required)"),
                );
            }
        }
    }
}

fn shannon_entropy(s: &str) -> f64 {
    let mut freq = [0u32; 256];
    let len = s.len() as f64;
    for &b in s.as_bytes() {
        freq[b as usize] += 1;
    }
    let mut entropy = 0.0f64;
    for &count in &freq {
        if count > 0 {
            let p = count as f64 / len;
            entropy -= p * p.log2();
        }
    }
    entropy
}

fn has_secret_prefix(s: &str) -> bool {
    // Known prefixes for API keys and tokens
    s.starts_with("sk-")         // OpenAI, Stripe
        || s.starts_with("sk_")  // Stripe
        || s.starts_with("pk_")  // Stripe public
        || s.starts_with("ghp_") // GitHub PAT
        || s.starts_with("gho_") // GitHub OAuth
        || s.starts_with("ghu_") // GitHub user-to-server
        || s.starts_with("ghs_") // GitHub server-to-server
        || s.starts_with("ghr_") // GitHub refresh
        || s.starts_with("AKIA") // AWS access key
        || s.starts_with("eyJ")  // JWT (base64 of {"
        || s.starts_with("xoxb-") // Slack bot
        || s.starts_with("xoxp-") // Slack user
        || s.starts_with("xapp-") // Slack app
        || s.starts_with("glpat-") // GitLab PAT
        || s.starts_with("npm_")   // npm token
        || s.starts_with("pypi-")  // PyPI token
        || s.starts_with("hf_")    // HuggingFace
        || s.starts_with("sq0")    // Square
        || s.starts_with("SG.")    // SendGrid
        || s.starts_with("whsec_") // Stripe webhook
}

fn make_environ_ref(var_name: &str) -> String {
    let mut s = String::from("os.environ[\"");
    s.push_str(var_name);
    s.push_str("\"]");
    s
}

fn truncate_secret(s: &str) -> String {
    if s.len() <= 12 {
        return "\"***\"".to_string();
    }
    let prefix: String = s.chars().take(8).collect();
    format!("\"{prefix}...\"")
}

#[cfg(test)]
mod tests {
    use super::*;
    use codeguard_ast::parse_python;
    use std::path::PathBuf;

    fn lint(source: &str) -> Vec<Diagnostic> {
        let tree = parse_python(source).unwrap();
        lint_vibe(&tree, source, &PathBuf::from("test.py"))
    }

    #[test]
    fn test_hardcoded_secret() {
        let d = lint(r#"API_KEY = "sk-proj-abc123def456""#);
        assert!(!d.is_empty());
        assert_eq!(d[0].code.0, "VC001");
    }

    #[test]
    fn test_no_false_positive_env() {
        let d = lint(r#"API_KEY = os.environ["API_KEY"]"#);
        let vc001: Vec<_> = d.iter().filter(|d| d.code.0 == "VC001").collect();
        assert!(vc001.is_empty());
    }

    #[test]
    fn test_ai_comment() {
        let d = lint("# Generated by Claude\nx = 1");
        let vc002: Vec<_> = d.iter().filter(|d| d.code.0 == "VC002").collect();
        assert_eq!(vc002.len(), 1);
    }

    #[test]
    fn test_debug_print() {
        let d = lint("print('debug')");
        let vc003: Vec<_> = d.iter().filter(|d| d.code.0 == "VC003").collect();
        assert_eq!(vc003.len(), 1);
    }

    #[test]
    fn test_pdb_import() {
        let d = lint("import pdb");
        let vc004: Vec<_> = d.iter().filter(|d| d.code.0 == "VC004").collect();
        assert_eq!(vc004.len(), 1);
    }

    #[test]
    fn test_ipdb_import() {
        let d = lint("import ipdb");
        let vc004: Vec<_> = d.iter().filter(|d| d.code.0 == "VC004").collect();
        assert_eq!(vc004.len(), 1);
    }

    #[test]
    fn test_breakpoint_call() {
        let d = lint("breakpoint()");
        let vc003: Vec<_> = d.iter().filter(|d| d.code.0 == "VC003").collect();
        assert_eq!(vc003.len(), 1);
    }

    #[test]
    fn test_pdb_set_trace() {
        let d = lint("import pdb\npdb.set_trace()");
        let vc003: Vec<_> = d.iter().filter(|d| d.code.0 == "VC003").collect();
        assert_eq!(vc003.len(), 1);
    }

    #[test]
    fn test_console_log() {
        let d = lint("console.log('test')");
        let vc003: Vec<_> = d.iter().filter(|d| d.code.0 == "VC003").collect();
        assert_eq!(vc003.len(), 1);
    }

    #[test]
    fn test_no_false_positive_logging() {
        // logging.info() should NOT trigger VC003
        let d = lint("import logging\nlogging.info('test')");
        let vc003: Vec<_> = d.iter().filter(|d| d.code.0 == "VC003").collect();
        assert_eq!(vc003.len(), 0);
    }

    #[test]
    fn test_no_false_positive_normal_string() {
        let d = lint(r#"name = "hello world""#);
        let vc001: Vec<_> = d.iter().filter(|d| d.code.0 == "VC001").collect();
        assert_eq!(vc001.len(), 0);
    }

    #[test]
    fn test_password_secret() {
        let d = lint(r#"PASSWORD = "hunter2""#);
        let vc001: Vec<_> = d.iter().filter(|d| d.code.0 == "VC001").collect();
        assert_eq!(vc001.len(), 1);
    }

    #[test]
    fn test_token_secret() {
        let d = lint(r#"AUTH_TOKEN = "abc123""#);
        let vc001: Vec<_> = d.iter().filter(|d| d.code.0 == "VC001").collect();
        assert_eq!(vc001.len(), 1);
    }

    #[test]
    fn test_secret_autofix_has_environ() {
        let d = lint(r#"API_KEY = "sk-proj-abc123""#);
        let vc001: Vec<_> = d.iter().filter(|d| d.code.0 == "VC001").collect();
        assert_eq!(vc001.len(), 1);
        let fix = vc001[0].fix.as_ref().unwrap();
        assert!(fix.replacement.contains("os.environ"));
        assert!(fix.replacement.contains("API_KEY"));
    }

    #[test]
    fn test_ai_comment_variants() {
        let tests = vec![
            "# TODO: Claude suggested this approach",
            "# Generated by Copilot",
            "# ChatGPT wrote this function",
            "# AI generated code below",
            "# This was made by GPT-4",
        ];
        for src in tests {
            let full = format!("{src}\nx = 1");
            let d = lint(&full);
            let vc002: Vec<_> = d.iter().filter(|d| d.code.0 == "VC002").collect();
            assert_eq!(vc002.len(), 1, "Failed for: {src}");
        }
    }

    #[test]
    fn test_no_false_positive_normal_comment() {
        let d = lint("# This is a normal TODO: fix this later\nx = 1");
        let vc002: Vec<_> = d.iter().filter(|d| d.code.0 == "VC002").collect();
        assert_eq!(vc002.len(), 0);
    }

    #[test]
    fn test_empty_secret_no_trigger() {
        let d = lint(r#"API_KEY = """#);
        let vc001: Vec<_> = d.iter().filter(|d| d.code.0 == "VC001").collect();
        assert_eq!(vc001.len(), 0);
    }

    #[test]
    fn test_multiple_issues_same_file() {
        let source = r#"
import pdb
API_KEY = "secret123"
# Generated by Claude
print("debug")
breakpoint()
"#;
        let d = lint(source);
        assert!(d.len() >= 4); // VC004 + VC001 + VC002 + VC003 + VC003
    }
}
